name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          if ! [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: TAG '$TAG' does not match expected pattern 'v[0-9]+\.[0-9]+\.[0-9]+$'"
            exit 1
          fi
          gh release create "$TAG" \
            --repo "${{ github.repository }}" \
            --title "${TAG#v}" \
            --generate-notes
